export enum ServiceKeys {
  LOGIN = 'LOGIN',
  CREATE_USER = 'CREATE_USER',
  GET_USER = 'GET_USER',
  FIND_USER = 'FIND_USER',
  CREATE_BOOK = 'CREATE_BOOK',
  UPDATE_BOOK = 'UPDATE_BOOK',
  DELETE_BOOK = 'DELETE_BOOK',
  GET_BOOK = 'GET_BOOK',
  GET_BOOK_INFO = 'GET_BOOK_INFO',
  RENT_BOOK = 'RENT_BOOK',
}
